# Docker compose definition to run NexusDocs in production mode, so no mounted
# code, no dev containers etc. Only this single file and some configuration files are required.

version: '3'

services:

  elasticsearch:
    container_name: nds-elasticsearch
    image: nexushubs/elasticsearch-cn:latest
    restart: always
    volumes:
      - elasticsearch-data

  mongodb:
    container_name: nds-mongodb
    image: mongo:3.6
    restart: always
    volumes:
      - mongodb-data

  unoconv:
    container_name: nds-unoconv
    image: alphakevin/unoconv-server:latest
    restart: always

  pandoc:
    container_name: nds-pandoc-api
    image: alphakevin/pandoc-api:latest
    restart: always

  pdf2image:
    container_name: nds-pdf2image
    image: nexushubs/pdf2image:latest
    restart: always
    environment:
      MONGO_URL: mongodb://mongodb/pdf2image

  nds:
    container_name: nds-main
    image: nexushubs/nexusdocs:latest
    restart: always
    environment:
      NDS_DATABASE: mongodb://mongodb/nexusdocs
      UNOCONV_SERVER_URL: http://unoconv:4000
      PANDOC_API_URL: http://pandoc:4000
      ELASTICSEARCH_HOST: elasticsearch
      PDF2IMAGE_URL: http://pdf2image:3000
      PDF2IMAGE_MQTT: mqtt://pdf2image:1833
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
      - unoconv
      - elasticsearch
      - pdf2image

volumes:
  elasticsearch-data:
  mongodb-data:
