# Docker compose definition to run NexusDocs in production mode, so no mounted
# code, no dev containers etc. Only this single file and some configuration files are required.

version: '3'

services:

  elasticsearch:
    container_name: nds-elasticsearch
    image: nexushubs/elasticsearch-cn:latest
    restart: always

  mongo:
    container_name: nds-mongodb
    image: mongo:3.6
    restart: always

  unoconv:
    container_name: nds-unoconv
    image: alphakevin/unoconv-server:latest
    restart: always

  pdf2image:
    container_name: nds-pdf2image
    image: nexushubs/pdf2image:latest
    restart: always

  nds:
    container_name: nds-main
    image: nexushubs/nexusdocs:latest
    restart: always
    environment:
      NDS_DATABASE: mongodb://mongo/nexusdocs
      UNOCONV_SERVER_URL: http://unoconv:4000
      ELASTICSEARCH_HOST: elasticsearch
      PDF2IMAGE_URL: http://pdf2image:3000
      PDF2IMAGE_MQTT: mqtt://pdf2image:1833
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - mongo
      - unoconv
      - elasticsearch
      - pdf2image
