# Docker compose definition to run NexusDocs in production mode, so no mounted
# code, no dev containers etc. Only this single file and some configuration files are required.

version: '3'

services:

  elasticsearch:
    container_name: nexusdocs-elasticsearch
    image: nexushubs/elasticsearch-cn
    restart: always
    volumes:
      - ./data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./database/elasticsearch:/usr/share/elasticsearch/data:rw

  mongo:
    container_name: nexusdocs-mongodb
    image: mongo:3.6
    restart: always
    volumes:
      - ./database:/data/db:rw

  nds:
    container_name: nexusdocs-server
    image: nexushubs/nexusdocs
    restart: always
    environment:
      NDS_DATABASE: mongodb://mongo/nexusdocs
      UNOCONV_SERVER_URL: http://unoconv:4000
      ELASTICSEARCH_HOST: elasticsearch
      FILE_CACHE_CLEAR_ON_STARTUP: 0
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - mongo
      - unoconv

  unoconv:
    container_name: nexusdocs-unoconv
    image: alphakevin/unoconv-server
    restart: always
    ports:
      - '127.0.0.1:5000:4000'
